#!/bin/sh

redshift -P -O 6000 && echo 6000 > "$REDSHIFT_CACHE"
xrdb /home/lucas/.config/X11/Xresources

xrandr.sh auto

dunst &
picom &
sxhkd &
urxvtd &
clipsim --daemon &
events.bash &

dwmblocks2 &

xset m 1 1 &
setkeymap.sh br_lucas

# /etc/X11/xorg.conf.d/00-keyboard.conf
# Section "InputClass"
#     Identifier "system-keyboard"
#     MatchIsKeyboard "on"
#     Option "XkbLayout" "br_lucas_mior"
#     Option "XkbOptions" "caps:swapescape"
#     Option "AutoRepeat" "0 0"
# EndSection

sleep 1
wallpaper.bash
exec dwm

#export DESKTOP_SESSION=plasma
#exec startplasma-x11
