vim9script

# set verbosefile=vimlog.txt
# set verbose=7
set nocompatible

set undodir=/home/lucas/.local/share/vim/undo
set directory=/home/lucas/.local/share/vim/swap
set backupdir=/home/lucas/.local/share/vim/backup
set viewdir=/home/lucas/.local/share/vim/view
set runtimepath=/home/lucas/.config/vim,$VIMRUNTIME,
set runtimepath+=/home/lucas/.config/vim/after
filetype off
set runtimepath+=/usr/share/vim/vimfiles/
filetype on
syntax on
set viminfo+=n/home/lucas/.local/share/vim/viminfo

source /home/lucas/.config/vim/quit.vim

call plug#begin('~/.config/vim/plugged')

Plug 'preservim/tagbar'
Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'yegappan/lsp'
Plug 'ap/vim-css-color'
Plug 'romainl/vim-cool'
Plug 'dahu/vim-fanfingtastic'
Plug 'vim-python/python-syntax'
Plug 'lervag/vimtex'
Plug 'ahf/cocci-syntax'
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-function'

call plug#end()

command! Picon exe 'normal m`'
                \ | silent! undojoin | exe '%!picon -a' | exe 'normal ``'

packadd termdebug
nnoremap <buffer> <C-@> :Break<CR>
nnoremap <buffer> <leader>c :Continue<CR>
nnoremap <buffer> <space>   :Step<CR>
nnoremap <buffer> <enter>   :Step<CR>

augroup CDebug
    autocmd!
    au CursorHold *.c call g:EvalSmart()
augroup END

g:term_debug_on = v:false

autocmd User TermdebugStartPost g:term_debug_on = v:true
autocmd User TermdebugStopPre   g:term_debug_on = v:false

def g:EvalSmart(): void
    if !g:term_debug_on
        return
    endif
    var save_pos = getcurpos()

    var lnum = line('.')
    var text = getline(lnum)

    if text =~ '^#'
        setpos('.', save_pos)
        return
    endif

    var c_keywords = [
        'if', 'else', 'while', 'for', 'do', 'switch', 'case', 'default',
        'break', 'continue', 'return', 'goto',
        'sizeof', 'typedef', 'struct', 'union', 'enum',
        'static', 'extern', 'auto', 'register',
        'const', 'volatile', 'restrict',
        'void', 'bool', 'char', 'short', 'int', 'long',
        'float', 'double', 'signed', 'unsigned',
    ]

    var colnum = col('.')
    var lastcol = len(text)

    while colnum <= lastcol
        if text[colnum - 1] =~ '[_0-9A-Za-z]'
            var start = colnum
            var end = colnum

            while end <= lastcol && text[end - 1] =~ '[_0-9A-Za-z]'
                end += 1
            endwhile

            var ident = text[start - 1 : end - 2]

            if index(c_keywords, ident) >= 0
                colnum = end
                continue
            endif

            var tags = taglist('^' .. ident .. '$')
            var is_typedef = v:false

            for tag in tags
                if get(tag, 'kind', '') ==# 't'
                    is_typedef = v:true
                    break
                endif
            endfor

            if !is_typedef
                cursor(lnum, start)
                execute 'Eval'
                break
            endif

            colnum = end
            continue
        endif

        colnum += 1
    endwhile

    setpos('.', save_pos)
enddef

g:vimtex_view_enabled = 0
g:vimtex_view_Auto = 0

g:airline#extensions#tabline#enabled = 0
g:airline#extensions#tagbar#enabled = 1
g:airline#extensions#tagbar#searchmethod = 'scoped-stl'
g:airline#extensions#tagbar#flags = ''
g:airline#parts#ffenc#skip_expected_string = 'utf-8[unix]'

legacy function AirlineThemePatch(palette)
    let l:fg_g = synIDattr(synIDtrans(hlID('Function')), 'fg', 'gui')
    let l:fg_c = synIDattr(synIDtrans(hlID('Function')), 'fg', 'cterm')

    " Fallback to default Cyan if synIDattr returns empty or invalid
    if empty(l:fg_g) || l:fg_g ==# '-1'
        let l:fg_g = '#00aaaa'
    endif
    if empty(l:fg_c) || l:fg_c ==# '-1'
        let l:fg_c = '6'
    endif

    let a:palette.accents.tagbar_function = [
        \ l:fg_g,
        \ '',
        \ l:fg_c,
        \ '',
        \ ''
        \ ]
endfunction

g:airline_theme_patch_func = 'AirlineThemePatch'

airline#parts#define_accent('tagbar', 'tagbar_function')

# Tagbar layout configuration
g:tagbar_left = 1
g:tagbar_width = 40
g:tagbar_sort = 0

# Automatically open/close Tagbar based on terminal width
def ToggleTagbarOnSize(): void
    if &columns > 90
        if !tagbar#IsOpen()
            execute 'TagbarOpen'
            wincmd p
        endif
    else
        if tagbar#IsOpen()
            execute 'TagbarClose'
        endif
    endif
enddef

augroup AutoTagbarResize
    autocmd!
    autocmd VimEnter,VimResized * ToggleTagbarOnSize()
augroup END

g:DiffColors = 1

g:gitgutter_signs = 1
g:gitgutter_highlight_lines = 1
g:gitgutter_highlight_linenrs = 0
g:gitgutter_sign_added = '+'
g:gitgutter_sign_modified = '~'
g:gitgutter_sign_removed = '-'
g:gitgutter_sign_removed_first_line = '^'
g:gitgutter_sign_removed_above_and_below = '{'
g:gitgutter_sign_modified_removed = 'w'
g:gitgutter_set_sign_backgrounds = 1
g:gitgutter_map_keys = 0
g:gitgutter_terminal_reports_focus = 0

# fugitive
nnoremap <leader>g :tab Git<CR>
nnoremap <C-g>     :!gitwip.sh % <CR>

g:python_highlight_all = 1

set tags=tags

def g:Gototo(): void
    var cur_win = win_getid()
    var pos = getcurpos()

    silent! LspGotoDefinition

    if getcurpos() ==# pos
        var word = expand('<cword>')
        var word_escaped = escape(word, '\')
        execute 'tag ' .. word_escaped
        return
    endif

    var new_win = win_getid()

    if new_win != cur_win
        var buf = expand('%:p')
        var saved_pos = getcurpos()
        close
        execute 'edit ' .. fnameescape(buf)
        setpos('.', saved_pos)
    endif
    return
enddef
nnoremap <C-]> :call g:Gototo()<CR>

nnoremap <leader>l :LspDiagNextWrap<CR>
nnoremap <leader>L :LspDiagPrev<CR>
nnoremap <leader>o :LspHover<CR>

def g:GitGutterNextHunkCycle(): void
    var line_num = line('.')
    execute 'GitGutterNextHunk'
    if line('.') ==# line_num
        cursor(1, 1)
        execute 'GitGutterNextHunk'
    endif
    return
enddef

nnoremap <leader>p :call g:GitGutterNextHunkCycle()<CR>
nnoremap <leader>u :GitGutterUndoHunk<CR><CR>

def g:ToggleMarkdownListItem(): void
    var cursor_line = line('.')
    var line_text = getline(cursor_line)

    if line_text =~ '^\s*\([-*]\|[0-9]\+\.\)\s\+'
        var new_line: string

        if line_text =~ '^\s*\([-*]\|[0-9]\+\.\)\s\+\~\~.*\~\~$'
            new_line = substitute(
                           line_text,
                           '^\(\s*\([-*]\|[0-9]\+\.\)\)\s\+\~\~\(.*\)\~\~$',
                           '\1 \3',
                           ''
                       )
        else
            new_line = substitute(
                           line_text,
                           '^\(\s*\([-*]\|[0-9]\+\.\)\)\s\+\(.*\)$',
                           '\1 ~~\3~~',
                           ''
                       )
        endif

        setline(cursor_line, new_line)
    endif
    return
enddef
# <C-@> is <C-Space> (for what I am sure is a very good reason)
augroup MarkdownListToggle
    autocmd!
    autocmd FileType markdown
        \ nnoremap <buffer> <C-@> :call g:ToggleMarkdownListItem()<CR>
augroup END

augroup SyncTexGroup
    autocmd!
    autocmd FileType tex call SyncTexSetupAuto()
augroup END

def SyncTexSetupAuto(): void
    autocmd CursorHold <buffer> silent! call SyncTexAutoForward()

    nnoremap <buffer> <Space> :call <SID>SyncTexForward()<CR>
    nnoremap <buffer> <leader>s :call <SID>SyncTexToggleAutoForward()<CR>
    set scrolloff=100
    return
enddef

def g:SyncTexBackward(line: string, afile: string): void
    synctex_auto_forward_disable = v:true
    silent! execute 'edit +' .. line .. ' ' .. afile
    # redraw!
    return
enddef

def SyncTexForward(): void
    var cmd = [
        'zf',
        'line=' .. string(line('.')),
        'col='  .. string(col('.')),
        'file=' .. fnameescape(bufname('%'))
    ]
    job_start(cmd)
enddef

def SyncTexAutoForward(): void
    if synctex_auto_forward_enable && !synctex_auto_forward_disable
        SyncTexForward()
    endif
    return
enddef

def SyncTexToggleAutoForward(): void
    synctex_auto_forward_enable = !synctex_auto_forward_enable
    if synctex_auto_forward_enable && !synctex_auto_forward_disable
        echo 'SyncTex mode: ON'
    else
        echo 'SyncTex mode: OFF'
    endif
    return
enddef

var synctex_auto_forward_enable = v:false
var synctex_auto_forward_disable = v:false
var synctex_focus_timer = -1

def SyncTexOnFocusTimer(timer_id: number): void
    synctex_focus_timer = -1
    synctex_auto_forward_disable = v:false
    return
enddef

def g:SyncTexOnFocusGain(): void
    if synctex_focus_timer != -1
        timer_stop(synctex_focus_timer)
    endif
    synctex_focus_timer = timer_start(1000, 'SyncTexOnFocusTimer')
    return
enddef

def g:SyncTexOnFocusLost(): void
    if synctex_focus_timer != -1
        timer_stop(synctex_focus_timer)
        synctex_focus_timer = -1
    endif
    return
enddef

&t_fe = "\<Esc>[?1004h"
&t_fd = "\<Esc>[?1004l"
execute "set <FocusGained>=\<Esc>[I"
execute "set <FocusLost>=\<Esc>[O"

autocmd FocusGained *.tex call SyncTexOnFocusGain()
autocmd FocusLost   *.tex call SyncTexOnFocusLost()

# cursor: format and color (terminal has to support these escape sequences)
&t_SI = &t_SI .. "\<Esc>[5 q\<Esc>]12;blue\x7"
&t_EI = &t_EI .. "\<Esc>[2 q\<Esc>]12;yellow\x7"

set history=1000
set titlelen=0  # don't limit title length
set autowrite
set breakindent autoindent smartindent
set breakindentopt=sbr showbreak=>
set cpoptions+=n
set commentstring=#%s
set shell=/usr/bin/zsh
# set hidden
set noswapfile
set timeoutlen=10000 ttimeoutlen=5
set updatetime=100
set history=10000
set clipboard^=unnamedplus,unnamed
set mouse=a
set mousemodel=popup
set dictionary="/usr/share/dict/words"
set foldmethod=marker foldmarker={,} foldminlines=1 foldlevelstart=100

# Interface
if exists('+termguicolors')
    &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
    set background=dark
endif
set laststatus=1 showtabline=1 noshowmode showcmd
set number relativenumber
set cursorline cursorcolumn #deixa o VIM lento
set scrolloff=5
set visualbell t_vb=
set splitbelow
set splitright
set wrap
set synmaxcol=300

# Find
set path+=**
set pumheight=12
set wildmenu
set wildmode=longest,full
set wildoptions=pum
set wildignore+=*.o
set completeopt=menu

set infercase
set hlsearch incsearch ignorecase smartcase
# Make n always search forward, even when started with ?
nnoremap <expr> n 'Nn'[v:searchforward]
nnoremap <expr> N 'nN'[v:searchforward]
# Formatar
set backspace=indent,eol,start
set tabstop=4 shiftwidth=4 expandtab
set textwidth=80
&colorcolumn = join(range(81, 999), ",")
set autoindent
set autoread
# set formatoptions-=c,r,o,/,b,n,i,j
set conceallevel=2
# set termwinsize=10x0
set noautochdir
autocmd CursorHold * checktime
filetype plugin on

def UpdateColorColumn()
    if &textwidth > 0
        # Method chaining (->) is very clean in Vim9
        &l:colorcolumn = range(&textwidth + 1, 999)->join(',')
    else
        &l:colorcolumn = ''
    endif
enddef

autocmd BufEnter,FileType * UpdateColorColumn()

colorscheme default
if &term =~ 'st\|xterm\|kitty\|alacritty\|tmux\|contour'
    &t_Ts = "\e[9m"   # Strikethrough
    &t_Te = "\e[29m"
    &t_Cs = "\e[4:3m" # Undercurl
    &t_Ce = "\e[4:0m"
endif

source /home/lucas/.config/vim/lspconfig.vim

g:mapleader = '\'
# set shortmess=at

command! Vmake w | silent make -j1 clang | unsilent redraw!
set makeprg=thebuild.sh\ nocolor
# nnoremap <leader>m :Vmake<CR>:LspDiag current<CR>
# nnoremap <leader>m :make<CR>:LspDiagNextWrap<CR>

def g:JumpToNextFileWithDiag()
    var current_file: string = expand('%:p')
    var c_files: list<string> = glob('src/*.c', false, true)
  
    if empty(c_files)
        return
    endif

    var absolute_files: list<string> = []
    for f in c_files
        var abs_path: string = fnamemodify(f, ':p')
        add(absolute_files, abs_path)
    endfor

    var current_idx: number = index(absolute_files, current_file)
    var start_idx: number = 0
    if current_idx != -1
        start_idx = current_idx
    endif

    var num_files: number = len(absolute_files)
  
    for i in range(1, num_files)
        var idx: number = (start_idx + i) % num_files
        var target: string = absolute_files[idx]
      
        execute 'hide edit ' .. target
      
        var placed: list<dict<any>> = sign_getplaced('', {group: '*'})
        var signs: list<dict<any>> = placed[0].signs
      
        if !empty(signs)
            try
                execute 'LspDiagNextWrap'
                return
            catch
                # If LspDiagNextWrap fails (e.g., signs are not from LSP), 
                # ignore the error and let the loop continue to the next file
            endtry
        endif
    endfor
  
    return
enddef

# nnoremap <leader>m :!CC=clang ./build.sh fast_feedback \|\| CC=clang ../build.sh fast_feedback<CR>call g:JumpToNextFileWithDiag()<CR>
nnoremap <leader>m :!CC=clang ./build.sh fast_feedback \|\| CC=clang ../build.sh fast_feedback<CR>
nnoremap <leader>j :call g:JumpToNextFileWithDiag()<CR>
# nnoremap <leader>m :make<CR>

# disable ex mode (what the hell is that shit?)
map Q <Nop>
# :help map-modes
nnoremap U u
nnoremap <C-z> u
inoremap <C-z> <esc>ui
vnoremap <C-c> y
vnoremap <C-x> d
vnoremap S :s/
nnoremap S :%s/

# hjkl;
# h é mapeado para f next (ver plugins)
noremap j h
noremap ; l
noremap k gj
noremap l gk

# some defaults dont make sense
nnoremap Y y$
nnoremap e ea
nnoremap cd 0D
nnoremap ' `
nnoremap ` '
inoremap <C-h> <esc>dbxi

# use global marks also for lowercase letters
for c in range(char2nr('a'), char2nr('z'))
  const uc = nr2char(c - 32)
  const lc = nr2char(c)

  execute printf('nnoremap m%s m%s', lc, uc)
  execute printf("nnoremap '%s `%s", lc, uc)
  execute printf("nnoremap `%s '%s", lc, uc)
endfor

# janela
nnoremap <C-k>  <C-w>w
nnoremap <C-l>  <C-l><C-w>w
tnoremap <C-k>  <C-w>w
tnoremap <C-l>  <C-l><C-w>w
nnoremap <C-w>j <C-w>h
nnoremap <C-w>k <C-w>j
nnoremap <C-w>l <C-w>k
nnoremap <C-w>; <C-w>l
nnoremap <C-w>J <C-w>H
nnoremap <C-w>K <C-w>J
nnoremap <C-w>L <C-w>K
nnoremap <C-w>: <C-w>L
inoremap <C-w>j <esc><C-w>h
inoremap <C-w>k <esc><C-w>j
inoremap <C-w>l <esc><C-w>k
inoremap <C-w>; <esc><C-w>l
inoremap <C-w>J <esc><C-w>H
inoremap <C-w>K <esc><C-w>J
inoremap <C-w>L <esc><C-w>K
inoremap <C-w>: <esc><C-w>L
vnoremap <C-w>j <esc><C-w>h
vnoremap <C-w>k <esc><C-w>j
vnoremap <C-w>l <esc><C-w>k
vnoremap <C-w>; <esc><C-w>l
vnoremap <C-w>J <esc><C-w>H
vnoremap <C-w>K <esc><C-w>J
vnoremap <C-w>L <esc><C-w>K
vnoremap <C-w>: <esc><C-w>L
tnoremap <C-w>j <esc><C-w>h
tnoremap <C-w>k <esc><C-w>j
tnoremap <C-w>l <esc><C-w>k
tnoremap <C-w>; <esc><C-w>l
tnoremap <C-w>J <esc><C-w>H
tnoremap <C-w>K <esc><C-w>J
tnoremap <C-w>L <esc><C-w>K
tnoremap <C-w>: <esc><C-w>L

# completions
inoremap <tab> <c-n>
inoremap <expr> <C-k> pumvisible() ? '<C-n>' : '<C-k>'
inoremap <expr> <C-l> pumvisible() ? '<C-p>' : '<C-l>'
cnoremap <expr> <C-k> pumvisible() ? '<C-n>' : '<C-k>'
cnoremap <expr> <C-l> pumvisible() ? '<C-p>' : '<C-l>'

autocmd BufWritePost ~/.config/X11/* !xrdb ~/.config/X11/Xresources
autocmd BufWritePost */nsxiv/key-handler             !nsxiv_keyhandler_update_lf.sed % > ~/.config/lf/nsxiv
autocmd BufWritePost */tmux/tmux.conf                 !tmux source-file %
autocmd BufWritePost */sxhkdrc                        !pkill -SIGUSR1 sxhkd
autocmd BufWritePost */dunst/dunstrc                  !killall dunst; setsid -f dunst 2>&1 > /dev/null
autocmd BufWritePost ~/.config/atalhos,*/atalhos.awk !atalhos.awk   ~/.config/atalhos
autocmd BufWritePost */ls_colors.css,*/ls_colors.awk !ls_colors.awk ~/.config/ls_colors.css
autocmd BufWritePost */lf_icons.conf,*/lf_icons.awk  !lf_icons.awk  ~/.config/lf_icons.conf
# autocmd BufWritePost */src/dwmblocks2/* !sudo ./build.sh install; restart.sh dwmblocks2

autocmd BufRead */Makefile,*.mk,
           \*/src/dmenu/*,*/src/sent/*,*/src/swarp/*,
           \*/src/lf/*,*/src/nsxiv/*,*/src/nsxiv-extra/* setlocal noexpandtab
autocmd BufRead */Makefile setlocal textwidth=80

augroup test_c_autocmd
  autocmd!
  autocmd BufWritePost */src/a_c/*.c !test_c_program.sh % "execute"
augroup END

autocmd BufWritePost */src/0wayland/*.c  !test_c_program.sh %
autocmd BufWritePost */src/a_c++/*.cpp   !g++ -Wall -Wextra -Wpedantic % -o /tmp/%.out && /tmp/%.out
autocmd BufWritePost */src/a_python/*.py !python %
autocmd BufWritePost */src/a_rust/*.rs   !rustc % -o /tmp/%.out && /tmp/%.out
# au BufWritePost *.kt !android_studio_shiftf9.sh

# au BufWritePost *.sh,*.bash,*.zsh,PKGBUILD,PKGBUILD.install   !shellcheck -e SC2059 -x %
def RunShellcheck(): void
    if &filetype ==# 'sh'
      execute '!shellcheck -e SC2059 -x ' .. fnameescape(expand('%:p'))
    endif
    return
enddef

autocmd BufWritePost * call RunShellcheck()

autocmd BufWritePost *.awk !gawk --lint -f %

autocmd BufRead,BufNewFile *.mo,*.mod          setlocal filetype=modelica
autocmd BufRead,BufNewFile *.sage              setlocal filetype=python
autocmd BufRead,BufNewFile /var/tmp/fstab* setlocal filetype=fstab
autocmd BufRead,BufNewFile *.sp,*.MOD          setlocal filetype=spice
autocmd BufRead,BufNewFile *.plt               setlocal filetype=gnuplot
autocmd BufRead,BufNewFile */X11/urxvt          setlocal filetype=xdefaults
autocmd BufRead,BufNewFile */.config/zathura/* setlocal filetype=zathurarc
autocmd BufRead,BufNewFile */src/cecup/*.c     setlocal textwidth=100
autocmd BufRead,BufNewFile */src/cecup/*.h     setlocal textwidth=100
autocmd BufRead,BufNewFile *.sent              setlocal filetype=sent
autocmd BufRead,BufNewFile *.sed               setlocal filetype=sed
autocmd BufRead,BufNewFile *.pgn               setlocal filetype=pgn
autocmd BufRead,BufNewFile */COMMIT_EDITMSG     setlocal filetype=gitcommit
autocmd BufRead,BufNewFile *.tab               setlocal filetype=tab
autocmd BufRead,BufNewFile */.config/lf/* setlocal filetype=lf
autocmd BufRead,BufNewFile ~/.config/* setlocal autochdir
autocmd BufRead,BufNewFile *.bib               setlocal autochdir

# cd to file dir on startup
# au VimEnter * lcd %:p:h

autocmd WinResized * wincmd =
# augroup Mkdir
#   autocmd!
#   autocmd BufWritePre * call mkdir(expand("<afile>:p:h"), "p")
# augroup END

def g:TriggerStBug(): void
    var cmd = 'fzf'
    var what = trim(system(cmd))
    return
enddef

def g:FzfFindFile(): void
    var buflist = []
    for buf in range(1, bufnr('$'))
        add(buflist, bufname(buf))
    endfor
    writefile(buflist, '/tmp/vimbuflist')

    var cmd =
           ' { /usr/bin/cat /tmp/vimbuflist;         '
        .. '   rg --files --no-messages;             '
        .. '   find .git/hooks -type f 2>/dev/null; }'
        .. '   | sed "s|^./||g"'
        .. '   | sort | uniq'
        .. '   | fzf --bind one:accept 2>/dev/null'

    var file = trim(system(cmd))

    delete('/tmp/vimbuflist')

    if file ==# ''
        redraw!
        return
    endif

    sleep 100m
    while getchar(0) != 0
        # wait until there are no chars to read
    endwhile

    execute 'edit ' .. fnameescape(file)
    redraw!
    return
enddef

nnoremap <C-f> :call g:FzfFindFile()<CR>

def g:FzfFindRegex(): void
    var preview_script = 'fzf_bat_preview.bash'

    # Add your exclusions here using -g '!pattern'
    # For example, excluding .git, binaries, and common TeX junk
    var cmd =
        'rg --line-number --no-heading'
        .. ' -g "!.git/*"'
        .. ' -g "!*.{o,bin,exe}"'
        .. ' -g "!*.{pdf,log,aux,bbl,blg,toc}"'
        .. ' -g "!package/{pkg,src}"'
        .. ' -g "!node_modules/*"'
        .. ' . 2>/dev/null'
        .. ' | fzf --delimiter ":"'
        .. '       --bind one:accept'
        .. '       --preview-window=up,80%,border-rounded'
        .. '       --preview "' .. preview_script .. ' {1} {2}"'

    var out = systemlist(cmd)

    while getchar(0) != 0
    endwhile
    redraw!

    if empty(out) || out[0] ==# ''
        return
    endif

    var parts = split(out[0], ':', v:false)
    if len(parts) < 2
        return
    endif

    var file_path = parts[0]
    var line_num = str2nr(parts[1])

    if filereadable(file_path)
        execute 'edit ' .. fnameescape(file_path)
        execute ':' .. line_num
        normal! zz
    endif

    redraw!
    return
enddef

nnoremap <C-h> :call g:FzfFindRegex()<CR>

# ignore diacritics on search a à á ã â ä A À Á Ã Â Ä \a
# cnoremap <CR>
#     \ <C-\>e getcmdtype() =~ '[?/]' ?
#          \ substitute(getcmdline(), '\%(\\\)\@<!\a', '[[=\0=]]', 'g') :
#          \ getcmdline()<CR><CR>

nnoremap <tab> :call g:SwitchOrFzf()<CR>
nnoremap <S-tab> gT

def g:SwitchOrFzf(): void
    var bufs = filter(range(1, bufnr('$')), (_, v) => buflisted(v))
    var ntabs = tabpagenr('$')

    if ntabs > 1
        execute 'normal gt'
        return
    endif

    if len(bufs) == 1
        g:FzfFindFile()
    elseif len(bufs) == 2
       var alt_buf = bufnr('#')
       execute 'buffer ' .. alt_buf
    else
        g:FzfFindFile()
    endif
enddef

def RightAlign(char: string)
    if strlen(char) > 1
        return
    endif

    var linelength: number = strlen(getline('.'))
    right
    var spaces: number = strlen(getline('.')) - linelength

    execute "normal 0|d" .. spaces .. "l"
    execute "normal f" .. char
    normal P

    return
enddef

command! -range -nargs=1 RightAlign :<line1>,<line2>call RightAlign(<args>)

def CopyFileWithHeader(is_visual: bool)
    var filename: string = expand('%:t')
    var header: string = ""
    var body: string = ""

    if is_visual
        header = $"some parts of {filename}:\n"
        var region = getregion(getpos("'<"), getpos("'>"))
        body = join(region, "\n")
    else
        header = $"{filename}:\n"
        var lines = getline(1, '$')

        if &filetype == 'c'
            var filtered: list<string> = []
            var skipping_comments = true

            for line in lines
                if skipping_comments
                    if line =~ '^\s*\(//\|/\*\|\s*\*\|\s*$\)'
                        continue
                    endif
                    skipping_comments = false
                endif

                if line =~ '^#if TESTING'
                    add(filtered, "// skipping #if TESTING block for brevity...")
                    break
                endif

                add(filtered, line)
            endfor
            body = join(filtered, "\n")
        else
            body = join(lines, "\n")
        endif
    endif

    setreg('+', header .. body)
    echomsg "Copied to clipboard with header."
enddef

nnoremap <silent> <leader>fc <ScriptCmd>CopyFileWithHeader(false)<CR>
xnoremap <silent> <leader>fc <ScriptCmd>CopyFileWithHeader(true)<CR>

source /home/lucas/.config/vim/.arquivos.vim
source /home/lucas/.config/vim/cores.vim
