set nocompatible

set undodir=/home/lucas/.local/share/vim/undo
set directory=/home/lucas/.local/share/vim/swap
set backupdir=/home/lucas/.local/share/vim/backup
set viewdir=/home/lucas/.local/share/vim/view
set runtimepath=/home/lucas/.config/vim,$VIMRUNTIME,
set runtimepath+=/home/lucas/.config/vim/after
filetype off
set runtimepath+=/usr/share/vim/vimfiles/
filetype on
syntax on
let $MYVIMRC="/home/lucas/.config/vim/vimrc"

source /home/lucas/.config/vim/settings.vim
source /home/lucas/.config/vim/quit.vim
source /home/lucas/.config/vim/plugins.vim
source /home/lucas/.config/vim/lspconfig.vim
source /home/lucas/.config/vim/mappings.vim
source /home/lucas/.config/vim/autocmds.vim
source /home/lucas/.config/vim/.arquivos.vim
source /home/lucas/.config/vim/cores.vim
source /home/lucas/.config/vim/vim9scriptmy.vim

set viminfo+=n/home/lucas/.local/share/vim/viminfo
