[Paths]
src=/home/lucas/vids/
dst=/media/toshiba/lucas/vids/

[Tools]
diff=unidiff.bash
term=st

[Filters]
new=true
hard=false
update=false
equal=false
delete=false
ignore=true

[Options]
check_fs=true
