[Paths]
src=/home/lucas/.local/src/cecup/a
dst=/home/lucas/.local/src/cecup/b

[Tools]
diff=unidiff.bash
term=st

[Filters]
new=true
hard=true
update=false
equal=false
delete=false
ignore=false

[Options]
check_fs=false
delete_after=true
delete_excluded=true
