[Paths]
src=/home/lucas/docs
dst=/media/sandisk/lucas/docs

[Tools]
diff=unidiff.bash
term=st

[Filters]
new=true
hard=true
update=false
equal=true
delete=false
ignore=false

[Options]
check_fs=false
delete_after=true
delete_ignored=false
