LF_ICONS+=':di=📂'
LF_ICONS+=':fi=📄'
LF_ICONS+=':ex=💲'
LF_ICONS+=':ln=🔗'
LF_ICONS+=':tw=🔒'
LF_ICONS+=':bd=💽'
LF_ICONS+=':rs=📄:mh=📄:pi=📄:so=📄:do=📄:cd=📄:mi=📄:su=📄:sg=📄:ca=📄:tw=📄:ow=📄:or=📄:st=📄:pi=📄'
LF_ICONS+=':down/=⬇️ :downloads/=⬇️ '
LF_ICONS+=':livros/=📚:*.lib=📚'
LF_ICONS+=':literatura/=📗'
LF_ICONS+=':história/=📜'
LF_ICONS+=':engenharia/=🎓'
LF_ICONS+=':sites/=🌍'
LF_ICONS+=':biocal/=🔥:biocal_burntech/=🔥'
LF_ICONS+=':mus/=🎶:musicas/=🎶'
LF_ICONS+=':vids/=🎞 :videos/=🎞 '
LF_ICONS+=':yt-dlp/=▶️ '
LF_ICONS+=':imgs/=🖼 :imagens/=🖼 :*.jpg=🖼 :*.jpeg=🖼 :*.png=🖼 :*.ico=🖼 :*.gif=🖼 :*.bmp=🖼 :*.ff=🖼 :*.webp=🖼 '
LF_ICONS+=':compras_online/=💸'
LF_ICONS+=':música/=🎼:cifras/=🎼:*.tab=🎼'
LF_ICONS+=':chess/=♟ :xadrez/=♟ :*.pgn=♟ :*.fen=♟ '
LF_ICONS+=':*.pt=🧠:*.h5=🧠'
LF_ICONS+=':*.aup=🎧'
LF_ICONS+=':academia/=🏋 '
LF_ICONS+=':ampera/=🏎 '
LF_ICONS+=':celesc/=⚡'
LF_ICONS+=':latex/=📜'
LF_ICONS+=':matemática/=➕'
LF_ICONS+=':*.aedt=🧲'
LF_ICONS+=':UFSC_engenharia_elétrica/=🎓'
LF_ICONS+=':scripts/=💲'
LF_ICONS+=':lixeira/=🗑 '
LF_ICONS+=':.config/=⚙ '
LF_ICONS+=':HMB/=⚔ '
LF_ICONS+=':burocracia/=🗃 '
LF_ICONS+=':README.md*=ℹ '
LF_ICONS+=':Makefile*=⚙ :*.mk=⚙ '
LF_ICONS+=':config.h*=⚙ :config.def.h*=⚙ :*.rasi=⚙ '
LF_ICONS+=':*.tar.bz=📦:*.tar.bz2=📦:*.tbz=📦:*.tbz2=📦'
LF_ICONS+=':*.tar.gz=📦:*.tgz=📦'
LF_ICONS+=':*.zip=📦:*.nar=📦:*.rar=📦:*.gz=📦'
LF_ICONS+=':*.gz=📦:*.7z=📦:*.zstd=📦'
LF_ICONS+=':*.iso=💿:*.img=💿'
LF_ICONS+=':win10/=🪟:windows10/=🪟:wbridge/=🪟:*.exe=🪟:*.dll=🪟'
LF_ICONS+=':prateado1T/=💽:toshiba/=💽'
LF_ICONS+=':wsandisk32/=💾:fita_ventoy/=💾:sandisk_ventoy/=💾'
LF_ICONS+=':*.xcf=🦊'
LF_ICONS+=':*.svg=💢'
LF_ICONS+=':*.mkv=🎞 :*.mp4=🎞 :*.mov=🎞 :*.avi=🎞 :*.wmv=🎞 :*.webm=🎞 :*.mpeg=🎞 :*.3gp=🎞 '
LF_ICONS+=':*.mp3=🎵:*.flac=🎵:*.opus=🎵:*.aac=🎵:*.ogg=🎵:*.wav=🎵:*.m3u=🎵:*.m4a=🎵'
LF_ICONS+=':*.mid=🎼'
LF_ICONS+=':*.mmpz=🎹'
LF_ICONS+=':*.pdf=📙:*.djvu=📙:*.epub=📙:*.ps=📙'
LF_ICONS+=':*.sent=📜:*.tex=📜:*.1=📜'
LF_ICONS+=':*.md=📑'
LF_ICONS+=':*.json=🗒️ '
LF_ICONS+=':*.yaml=⚙️ '
LF_ICONS+=':*.mo=▶️ :*.fmu=▶️ '
LF_ICONS+=':*.odt=📝:*.docx=📝'
LF_ICONS+=':*.odp=📺:*.pptx=📺'
LF_ICONS+=':*.ods=📉:*.xlsx=📉:*.csv=📉:*.tsv=📉'
LF_ICONS+=':*.hdr=🌍:*.exr=🌍'
LF_ICONS+=':*.diff=📃:*.patch=📃'
LF_ICONS+=':*.orig=📜'
LF_ICONS+=':*.rej=💥'
LF_ICONS+=':*.txt=🗒 '
LF_ICONS+=':*.bib=📚'
LF_ICONS+=':*.log=🔎'
LF_ICONS+=''
LF_ICONS+=''
LF_ICONS+=':*.html=🌎'
LF_ICONS+=':*.css=🎨'
LF_ICONS+=':*.vtt=🆎:*.srt=🆎'
LF_ICONS+=':*.o=💣:*.so=💣'
LF_ICONS+=':*.c=💻:*.cpp=💻:*.asm=💻:*.go=💻:*.zig=💻:*.f90=💻'
LF_ICONS+=':*.rs=🦀:*.rlib=🦀:rustlings/=🦀'
LF_ICONS+=':*.h=💻:*.hpp=💻'
LF_ICONS+=':*.ino=🦠'
LF_ICONS+=':*.awk=💲:*.pl=💲:*.py=💲:*.vim=💲:*.rb=💲'
LF_ICONS+=':*.ipynb=🐍'
LF_ICONS+=':*.sh=🐚:*.bash=🐚:*.zsh=🐚'
LF_ICONS+=':*.fish=🐟'
LF_ICONS+=':*.m=➗:*.r=➗:*.sci=➗'
LF_ICONS+=':*.lua=🌕'
LF_ICONS+=':*.kicad_sch=📈:*.sch=📈'
LF_ICONS+=':*.kicad_pcb=💹'
LF_ICONS+=':*.kicad_pro=📁'
LF_ICONS+=':*.kicad_mod=👣'
LF_ICONS+=':*.step=🧩:*.blend=🧩:*.stl=🧩'
LF_ICONS+=':*.drl=🔩'
LF_ICONS+=':*.gbr=💹'
LF_ICONS+=':*.gbrjob=🛠️ '
LF_ICONS+=':*.sp=🕸 '
LF_ICONS+=':*.gpg=🔒'
LF_ICONS+=':*.apk=📱'
LF_ICONS+=':*.plt=📊'
LF_ICONS+=':*.data=🔢'
LF_ICONS+=':*.part=🔻:*.crdownload=🔻'
LF_ICONS+=':*.torrent=🔽'
LF_ICONS+=':*.js=💩:*.aux=💩:*.bbl=💩:*.bcf=💩:*.blg=💩:*.doc=💩:*.xls=💩:*.ppt=💩'
LF_ICONS+=':*.~1~=💥:*.~2~=💥:*.~3~=💥:*.~4~=💥:*.~5~=💥:*.~6~=💥:*.~7~=💥:*.~8~=💥:*.~9~=💥'
export LF_ICONS